### PR TITLE
update to latest SignalR (1.0.0-rc2)

### PR DESCRIPTION
**Pull request by dominiqueplante**
make updates make it work with latest SignalR 1.0.0-rc2

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
Awesome PR!  Sadly the current version of ShootR is actually on a newer version of SignalR-rc2 (a dev build).  I'll be updating it to 1.0 once it's released.  Definitely appreciate the help though =]

**Comment by dominiqueplante** [comment]
Thanks for writing back!  I totally understand!  It's a great idea BTW

It doesn't surprise me there is a later build of signalr (1.0 seems imminent).

I've been meaning to look at the code and it only took a bit of tweaking to get it up and running on my laptop.

In your opinion, what area the needs most refactoring?

oh and BTW Kudos to David Fowler - he was ost helpful in the Jabbr room today in giving the good tips on where to find potential errors

**Comment by NTaylorMullen** [comment]
Thanks!

If you're looking to do some re-factoring I'd take a look at the interpolation logic ( I hacked it together ).  It's spread among the ShipController.ts and the ShipManager.ts classes.  That code is so fail =]

**Comment by NTaylorMullen** [comment]
Just updated to SignalR 1.0.0.  It's not on the server yet (i'm on bad internet right now) but will be either later tonight or tomorrow.

**Comment by dominiqueplante** [comment]
great to hear back!  I will check out those classes, and congrats on getting it running on SignalR 1.0.0.

I was showing a coworker (running two browsers on the same box), and he thought it was really cool !

**Pull request closed without merging**
